INIT_SESSION = 'INIT_SESSION'
SET_MEASUREMENT_ID = 'SET_MEASUREMENT_ID'
START = 'START'
RANDMOVE = 'RAND_MOVE'
GLORIENTTES = 'GLORIENTTES'
STRAIGHTMOVE = 'STRAIGHT_MOVE_'
STRAIGHTMOVE_BACKWARDS = 'STRAIGHT_MOVE_BW_'
SPIN = 'SPIN_'
SPIN_CLOCKWISE = 'SPIN_CW_'

MEASURE = 'MEASURE'  # playrec with source and receiver on the same robot
PLAYBACK_SWEEP = 'PLAYBACK_SWEEP'
START_RECORDING = 'START_RECORDING'
STOP_RECORDING = 'STOP_RECORDING'

ACK = 'ACK'

TYPE_ROBOT = 'r'
TYPE_META = 'm'

ROBOT_COMMANDS = [START, RANDMOVE, GLORIENTTES, STRAIGHTMOVE, STRAIGHTMOVE_BACKWARDS, SPIN, SPIN_CLOCKWISE]
META_COMMANDS = [INIT_SESSION, SET_MEASUREMENT_ID, MEASURE, PLAYBACK_SWEEP, START_RECORDING, STOP_RECORDING]
