#!/bin/sh
echo Switching directory...
cd /home/pi/ARTSRAM/ARTSRAMgit/AIRMSv2_py
echo Changing output volume...
amixer sset 'Headphone' 90%
echo Starting the Robot Server...
python3 robo_socket_server.py 1
sleep infinity
